version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planmore_app
    volumes:
      - ./:/var/www:cached     
      - /var/www/vendor           
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - planmore

  node:
    image: node:20
    container_name: planmore_node
    working_dir: /app
    volumes:
      - ./:/app:cached
      - /app/node_modules       
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - planmore

  web:
    image: nginx:stable-alpine
    container_name: planmore_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - planmore

  db:
    image: mysql:8.0
    container_name: planmore_db
    restart: always
    environment:
      MYSQL_DATABASE: planmore
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - planmore

networks:
  planmore:

volumes:
  dbdata:
